# Generated by Django 4.1.3 on 2022-11-23 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('usecase', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
