# Generated by Django 4.1.3 on 2022-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0002_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
