# Generated by Django 4.1.3 on 2022-11-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0003_alter_inventory_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='metadata',
        ),
    ]
