# Generated by Django 4.1.3 on 2022-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0004_delete_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_item',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inventory_item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
