# Generated by Django 4.1.3 on 2022-12-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0005_inventory_item_description_inventory_item_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_item_LocationID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_item_UsecaseID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usecase_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='inventory_item',
            name='full_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
