# Generated by Django 4.1.3 on 2022-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0006_inventory_item_locationid_inventory_item_usecaseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_item',
            name='full_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
