# Generated by Django 4.1.3 on 2023-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0007_alter_inventory_item_full_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
