# Generated by Django 4.1.3 on 2023-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0008_inventory_item_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=200)),
                ('paper_width', models.FloatField(default=1)),
                ('paper_height', models.FloatField(default=1)),
                ('print_file_name', models.CharField(default='label.pdf', max_length=200)),
            ],
        ),
    ]
