# Generated by Django 4.1.3 on 2023-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0009_inventory_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_settings',
            name='paper_orientation',
            field=models.CharField(default='landscape', max_length=200),
        ),
    ]
