# Generated by Django 4.1.3 on 2023-06-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0010_inventory_settings_paper_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_item',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
