# Generated by Django 4.1.3 on 2023-06-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0011_inventory_item_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Keys_for_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
