# Generated by Django 4.1.3 on 2023-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0012_api_keys_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys_for_users',
            name='auto_login_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='api_keys_for_users',
            name='api_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='api_keys_for_users',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
