# Generated by Django 4.1.3 on 2023-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0013_api_keys_for_users_auto_login_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_settings',
            name='paper_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
