# Generated by Django 4.1.3 on 2023-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0014_inventory_settings_paper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys_for_users',
            name='devices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
