# Generated by Django 5.0.4 on 2024-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0016_userclients_userprofile_delete_api_keys_for_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclients',
            name='hwkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
