# Generated by Django 5.0.4 on 2024-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0017_alter_userclients_hwkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclients',
            name='hwkey',
            field=models.IntegerField(default=0),
        ),
    ]
