# Generated by Django 5.0.4 on 2024-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0020_printserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='printserver',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
