# Generated by Django 5.0.4 on 2024-07-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0021_printserver_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclients',
            name='print_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_server', to='Inventory_mgmt.inventory_settings'),
        ),
    ]
