# Generated by Django 5.0.4 on 2024-07-11 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_mgmt', '0022_userclients_print_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclients',
            name='print_server',
        ),
        migrations.AddField(
            model_name='inventory_settings',
            name='print_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_server', to='Inventory_mgmt.printserver'),
        ),
    ]
